### PR TITLE
Access Control Refactor

### PR DESCRIPTION
**Pull request by dhovart**

### CODE REVIEW

**Review by r03ert0 — APPROVED** [review]
such nice code. The structure is crystal clear, and everything super well organised. Thank you!

**Review by katjaq — APPROVED** [review]
Thank you @dhovart This looks great! 
Thank you also for the details you gave on mattermost that the owner always has all access rights and that your implementation makes it more stable to possible inconsistent data from DB where "anyone" is not set because of some undesired side-effects. Fantastic ! 🚀

**Comment by dhovart** [comment]
Thank you!
@katjaq  @r03ert0 If you're ok with this, feel free to merge!!

https://github.com/neuroanatomy/BrainBox/pull/312 depends on this for tests to pass

**Comment by katjaq** [comment]
Fantastic!! 🚀 
Thanks! Merging!

**Pull request merged**
